# Generated by Django 4.2.11 on 2025-10-15 10:39

from django.db import migrations, models
import django.db.models.deletion
import publications_registry.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('license_agreement', models.BooleanField(default=False)),
                ('antiplagiarism_check', models.BooleanField(default=False)),
                ('article_status', models.CharField(choices=[('SUBMITTED', 'Zgłoszony'), ('PRESELECTION', 'Preselekcja'), ('ANTIPLAGIARISM', 'Antyplagiat'), ('REVIEW', 'Recenzje'), ('OK_FOR_PRINT', 'Skierowany do druku'), ('WITHDRAWN_BY_AUTHOR', 'Wycofany przez autora'), ('WITHDRAWN_FROM_ONLINE_ED', 'Wycofany z wydania online'), ('REJECTED', 'Odrzucony')], default='SUBMITTED', max_length=30)),
                ('issue', models.CharField(default=None, max_length=20, validators=[publications_registry.custom_validators.validate_issue_number])),
                ('method_of_submission', models.CharField(choices=[('OJS', 'Open Journal System'), ('EMAIL_EDITORIAL_BOARD', 'Email redakcji'), ('EMAIL_PRIVATE', 'Email prywatny')], max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('orcid', models.CharField(max_length=19, validators=[publications_registry.custom_validators.validate_orcid])),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('orcid', models.CharField(max_length=19, validators=[publications_registry.custom_validators.validate_orcid])),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Przyjąć do druku'), ('ACCEPT_CONDITIONALLY', 'Przyjąć do druku po poprawkach'), ('REJECT', 'Odrzucić')], max_length=30)),
                ('comments', models.TextField()),
                ('article_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.reviewer')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.author'),
        ),
    ]
