# Generated by Django 4.2.11 on 2025-10-17 11:20

from django.db import migrations, models
import django.db.models.deletion
import publications_registry.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, unique=True, verbose_name='Tytuł')),
                ('license_agreement', models.BooleanField(default=False, verbose_name='Umowa licencyjna')),
                ('antiplagiarism_check', models.BooleanField(default=False, verbose_name='Antyplagiat')),
                ('article_status', models.CharField(choices=[('SUBMITTED', 'Zgłoszony'), ('PRESELECTION', 'Preselekcja'), ('ANTIPLAGIARISM', 'Antyplagiat'), ('REVIEW', 'Recenzje'), ('OK_FOR_PRINT', 'Skierowany do druku'), ('WITHDRAWN_BY_AUTHOR', 'Wycofany przez autora'), ('WITHDRAWN_FROM_ONLINE_ED', 'Wycofany z wydania online'), ('REJECTED', 'Odrzucony')], default='SUBMITTED', max_length=30, verbose_name='Status artykułu')),
                ('issue', models.CharField(blank=True, default=None, max_length=20, validators=[publications_registry.custom_validators.validate_issue_number], verbose_name='Numer')),
                ('method_of_submission', models.CharField(choices=[('OJS', 'Open Journal System'), ('EMAIL_EDITORIAL_BOARD', 'Email redakcji'), ('EMAIL_PRIVATE', 'Email prywatny')], max_length=30, verbose_name='Sposób zgłoszenia')),
                ('comments', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('orcid', models.CharField(blank=True, max_length=19, unique=True, validators=[publications_registry.custom_validators.validate_orcid])),
                ('comments', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('orcid', models.CharField(max_length=19, validators=[publications_registry.custom_validators.validate_orcid])),
                ('comments', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Recnzent',
                'verbose_name_plural': 'Recenzenci',
            },
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Przyjąć do druku'), ('ACCEPT_CONDITIONALLY', 'Przyjąć do druku po poprawkach'), ('REJECT', 'Odrzucić')], max_length=30, verbose_name='Ocena')),
                ('comments', models.TextField(blank=True, verbose_name='Uwagi')),
                ('article_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.article', verbose_name='Tytuł')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.author', verbose_name='Autor')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.reviewer', verbose_name='Recenznet')),
            ],
            options={
                'verbose_name': 'Recenzja',
                'verbose_name_plural': 'Recenzje',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications_registry.author', verbose_name='Autor'),
        ),
    ]
