# Generated by Django 4.2.11 on 2025-10-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications_registry.author', verbose_name='Autor'),
        ),
    ]
